
    User.create(first_name: "Alan", last_name: "Martinez", username: "alanmartini", password_digest: Faker::Internet.password, email: "amartinez7@hotmail.com", avatar: 'https://ca.slack-edge.com/T02MD9XTF-U037WJF4JNT-6e0ec1934273-512', bio: 'Big martini lover. Let\'s share some good times over drinks!')
    User.create(first_name: "Christian", last_name: "Stringham", username: "cesalt", password_digest: Faker::Internet.password, email: "cstringer3@discord.com", avatar: 'https://ca.slack-edge.com/T02MD9XTF-U038GMSJND7-9e728f6366ae-512', bio: 'I love woodworking. Connect with me and be my muse. I promise I\'ll make you a good piece.')
    User.create(first_name: "Cristina", last_name: "Diaz", username: "lacristdiaz", password_digest: Faker::Internet.password, email: "diazcristina.2la@yahoo.com", avatar: 'https://ca.slack-edge.com/T02MD9XTF-U0394GNGC5U-811a6ed48f91-512', bio: 'she/her/ella. Los Angeles 4 life!!! HMU if you like the Dodgers :)')
    User.create(first_name: "Kevin", last_name: "Nielsen", username: "kevintheminer", password_digest: Faker::Internet.password, email: "knielson21@ethereum.org", avatar: 'https://ca.slack-edge.com/T02MD9XTF-U03AFKL6GE9-f29e5ed41800-512', bio: 'I\'ll teach you how to mine crypto. Too many GPU\'s on my hand. If you need one let me know!')
    User.create(first_name: "Eli", last_name: "Craig", username: "craigslisteli", password_digest: Faker::Internet.password, email: "ecraig@craigslist.com", avatar: 'https://ca.slack-edge.com/T03SGK1JQSH-U03SKJJ5MTL-c782bd138182-512', bio: 'I love music and I work for Spotify! Connect with me if you are also a music lover. Any and all genres!')
    User.create(first_name: "Mai", last_name: "Vang", username: "happymaivang", password_digest: Faker::Internet.password, email: "maivang06@gmail.com", avatar: 'https://ca.slack-edge.com/T02MD9XTF-U038F99SE77-1a6a72106fc9-512', bio: 'Hi, I\'m Mai! Big foodie so let\'s explore new food spots in town together!')
    User.create(first_name: "Leah", last_name: "Chen", username: "cssqueenleah", password_digest: Faker::Internet.password, email: "lchen331@gmail.com", avatar: 'https://ca.slack-edge.com/T02MD9XTF-U037XJAQM8S-e162a56bc9e1-512', bio: 'I can rewatch Grey\'s Anatomy over and over. Do not try to stop me.')
    User.create(first_name: "Isaac", last_name: "Lewkowicz", username: "isaakowicz", password_digest: Faker::Internet.password, email: "issacwithtwoas@global.net", avatar: 'https://ca.slack-edge.com/T02MD9XTF-U0361GE88CB-1c30845e1c5e-512', bio: 'Hi, my name is Isaac. Two A\'s, not two S\'s.')
    User.create(first_name: "Annemarie", last_name: "Lucernoni", username: "luccianne", password_digest: Faker::Internet.password, email: "lucernonia9@safari.io", avatar: 'https://ca.slack-edge.com/T02MD9XTF-U0397UDEEC8-0536e9a15278-512', bio: 'We will be friends instantly if you also love tacos the way I do. Also if you love the outdoors!')
    User.create(first_name: "Danko", last_name: "Karleusa", username: "gamerdanko", password_digest: Faker::Internet.password, email: "dankgames@faze.org", avatar: 'https://ca.slack-edge.com/T02MD9XTF-U02U0G01L1K-5dfb36ab9a79-512', bio: 'Big gamer!! Watch my streams on twitch I promise they will not disappoint you')
    User.create(first_name: "Jenna", last_name: "Hrdlicka", username: "jennaaah", password_digest: Faker::Internet.password, email: "hrdlickaj@huddle.com", avatar: 'https://ca.slack-edge.com/T02MD9XTF-U037MMZVCD6-527b2bd79a4b-512', bio: 'Extreme wine lover. Always available to go wine tasting. Don\'t be shy!')

puts "done seeding fren"
